//! Build script for the `ogit` crate.
//!
//! Walks `NTO/` and `SGO/` at compile time, emitting a single `ALL_TTLS`
//! const array into `$OUT_DIR/ttls.rs` for `src/lib.rs` to `include!`.
//! Pure `std` — no build-time crate deps.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let manifest_root = PathBuf::from(&manifest_dir);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = PathBuf::from(&out_dir).join("ttls.rs");

    let mut ttls: Vec<PathBuf> = Vec::new();
    for ontology_root in &["NTO", "SGO"] {
        let root = manifest_root.join(ontology_root);
        if root.is_dir() {
            walk(&root, &mut ttls);
        }
    }
    ttls.sort();

    let mut f = fs::File::create(&dest).expect("create ttls.rs");
    writeln!(f, "/// All embedded OGIT TTL files, generated by `build.rs`.").unwrap();
    writeln!(f, "///").unwrap();
    writeln!(f, "/// Count: {} files.", ttls.len()).unwrap();
    writeln!(f, "pub const ALL_TTLS: &[OgitTtl] = &[").unwrap();
    for path in &ttls {
        let rel = path.strip_prefix(&manifest_root).unwrap();
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let branch = branch_of(&rel_str);
        let kind = kind_of(&rel_str);
        // include_str! uses paths relative to the FILE doing the include —
        // since `lib.rs` does `include!(OUT_DIR/ttls.rs)`, the paths must be
        // absolute (CARGO_MANIFEST_DIR-prefixed) for include_str! to resolve.
        let abs = path.display().to_string().replace('\\', "/");
        writeln!(
            f,
            "    OgitTtl {{ path: \"{rel}\", branch: \"{branch}\", kind: TtlKind::{kind}, content: include_str!(\"{abs}\") }},",
            rel = rel_str,
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// Total count of embedded TTLs.").unwrap();
    writeln!(f, "pub const TTL_FILE_COUNT: usize = {};", ttls.len()).unwrap();

    println!("cargo:rerun-if-changed=NTO");
    println!("cargo:rerun-if-changed=SGO");
    println!("cargo:rerun-if-changed=build.rs");
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.extension().map_or(false, |e| e == "ttl") {
            out.push(path);
        }
    }
}

/// First two path components, e.g. `"NTO/Accounting"`. Falls back to first
/// component for SGO/ which has a different layout (SGO/core, SGO/ogit, ...).
fn branch_of(rel: &str) -> String {
    let parts: Vec<&str> = rel.splitn(4, '/').collect();
    if parts.len() >= 2 {
        format!("{}/{}", parts[0], parts[1])
    } else {
        parts[0].to_string()
    }
}

fn kind_of(rel: &str) -> &'static str {
    if rel.contains("/entities/") {
        "Entity"
    } else if rel.contains("/attributes/") {
        "Attribute"
    } else if rel.contains("/verbs/") {
        "Verb"
    } else {
        "Other"
    }
}
