//! # OGIT — Open Graph Intelligence Toolkit
//!
//! Rust crate exposing the OGIT ontology TTL files as embedded
//! `&'static str` constants. The crate is `no_std`-compatible — it carries
//! only `include_str!` data and a tiny lookup struct.
//!
//! The crate's contents are GENERATED by `build.rs` at compile time, which
//! walks `NTO/` and `SGO/` and emits a single `ALL_TTLS` array. Downstream
//! consumers (e.g. `lance-graph-contract`) can iterate that array in their
//! own `build.rs` to codegen typed const data from the TTL source.
//!
//! ## Distributed cross-ontology contract
//!
//! Each embedded TTL carries its own `@prefix` declarations + `ogit:allowed`
//! edge enumeration — the cross-ontology mapping is distributed across the
//! source TTLs, not maintained as a separate lookup table. This crate
//! preserves that property: it only ships the raw source; consumers derive
//! typed views from it without introducing a second copy that could drift.
//!
//! ## Usage
//!
//! ```ignore
//! use ogit::{ALL_TTLS, OgitTtl, TtlKind};
//!
//! for ttl in ALL_TTLS {
//!     if ttl.kind == TtlKind::Entity && ttl.branch == "NTO/Accounting" {
//!         println!("{}: {} bytes", ttl.path, ttl.content.len());
//!     }
//! }
//! ```

#![no_std]

/// One embedded OGIT TTL file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OgitTtl {
    /// Repository-relative path, e.g. `"NTO/Accounting/entities/JournalEntry.ttl"`.
    pub path: &'static str,
    /// First two path components, e.g. `"NTO/Accounting"`.
    pub branch: &'static str,
    /// Whether this TTL is under `entities/`, `attributes/`, `verbs/`, or other.
    pub kind: TtlKind,
    /// Raw TTL source text.
    pub content: &'static str,
}

/// Classification of the subdirectory the TTL was found in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TtlKind {
    /// `entities/` — `rdfs:Class subClassOf ogit:Entity`.
    Entity,
    /// `attributes/` — `owl:DatatypeProperty subPropertyOf ogit:Attribute`.
    Attribute,
    /// `verbs/` — `owl:ObjectProperty subPropertyOf ogit:Verb`.
    Verb,
    /// Anything else (top-level `ogit.ttl`, branch-level docs, etc.).
    Other,
}

// The build.rs walks the repo and writes `ALL_TTLS: &[OgitTtl]` here.
include!(concat!(env!("OUT_DIR"), "/ttls.rs"));

/// Convenience: filter `ALL_TTLS` to the given branch (e.g. `"NTO/Accounting"`).
///
/// Note: this is a linear scan (`ALL_TTLS.len()` ~ 1500). For hot paths
/// the consumer's own build.rs should generate a perfect-hash table.
pub fn by_branch(branch: &str) -> impl Iterator<Item = &'static OgitTtl> {
    ALL_TTLS.iter().filter(move |t| t.branch == branch)
}

/// Convenience: filter `ALL_TTLS` to one kind.
pub fn by_kind(kind: TtlKind) -> impl Iterator<Item = &'static OgitTtl> {
    ALL_TTLS.iter().filter(move |t| t.kind == kind)
}
